administrador/urls.py
from django.views.generic import TemplateView
from django.urls import path
from . import views


app_name = 'administrador'

urlpatterns = [
    path('',views.menu, name='menu'),  #Ruta para la ventana principal
    path('crear/', views.crear_persona, name='crear_persona'),
    path('editar/<int:id>/', views.editar_persona, name='editar_persona'),
    path('eliminar/<int:id>/', views.eliminar_persona, name='eliminar_persona'),
    path('listar/', views.listar_personas, name='listar_personas'),

    # PRODUCTOS
    # página principal de productos
    path('productos/', views.productos, name='productos'),

    # HTMX partials y endpoints
    path('producto/partials/listar/', views.listar_partial, name='listar_partial'),
    path('producto/partials/crear/', views.crear_partial, name='crear_partial'),
    path('producto/crear/htmx/', views.crear_htmx, name='crear_htmx'),
    path('producto/partials/editar/<int:pk>/', views.editar_partial, name='editar_partial'),
    path('producto/editar/<int:pk>/htmx/', views.editar_htmx, name='editar_htmx'),
    path('producto/eliminar/<int:pk>/', views.eliminar_htmx, name='eliminar_htmx'),


    #Rutas para compras
    path('compras/', views.lista_compras, name='lista_compras'),
    path('compras/crear/', views.crear_compra, name='crear_compra'),
    path('compras/<int:compra_id>/',views.detalle_compra, name='detalle_compra'),
    path('compras/editar/<int:compra_id>/', views.editar_compra, name='editar_compra'),
    path('compras/eliminar/<int:compra_id>/', views.eliminar_compra, name='eliminar_compra'),
    path('compras/<int:compra_id>/anular/', views.anular_compra, name='anular_compra'),


    #Rutas para stock
    path('stock/',views.lista_stock, name='lista_stock'),
    path('stock/crear/',views.crear_stock, name='crear_stock'),
    path('stock/editar/<int:stock_id>',views.editar_stock, name='editar_stock'),
    path('stock/eliminar/<int:stock_id>',views.eliminar_stock, name='eliminar_stock'),

    #Rutas para items
    path ('items/',views.lista_items, name='lista_items'),
    path('items/editar/<int:pk>/', views.editar_item, name='editar_item'),
    path('items/eliminar/<int:pk>/', views.eliminar_item, name='eliminar_item'),
    # CATEGORIAS
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/crear', views.crear_categorias, name='crear_categorias'),
    path('categorias/listar', views.listar_categorias_partial, name="listar_categorias_partial"),
    path('categorias/eliminar/<int:pk>/', views.eliminar_categoria, name='eliminar_categoria'),
    path('categorias/editar/<int:pk>/', views.editar_categoria, name='editar_categoria'),

    # INGREDIENTES DE PRODUCTOS
    path('ingredientes/<int:id>/', views.ingredientes, name='ingredientes'),
    path('cargar-items/', views.cargar_items, name="cargar_items"),
    path('ingredientes/<int:producto_id>/agregar', views.agregar_ingredientes, name='agregar_ingredientes'),
    path('ingredientes/<int:producto_id>/listar/', views.listar_ingredientes, name='listar_ingredientes'),
    path('ingredientes/eliminar/<int:pk>/', views.eliminar_ingrediente, name='eliminar_ingrediente'),
    # INGREDIENTES EDITAR INLINE
    path('ingredientes/<int:pk>/editar-form/', views.editar_ingrediente_form, name='editar_ingrediente_form'),
    path('ingredientes/<int:pk>/actualizar/', views.actualizar_ingrediente, name='actualizar_ingrediente'),
    path('ingredientes/<int:pk>/ver/', views.ver_fila_ingrediente, name='ver_fila_ingrediente'),

]

burgerSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('administrador.urls')),
    path('facturacion/', include('facturacion.urls')),
    path('pedidos/', include(('pedidos.urls', 'pedidos'), namespace='pedidos')),
    path('usuarios/', include('usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pedidos/urls.py
from django.urls import path
from .import views

app_name = 'pedidos'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/', views.menu_productos, name='menu_productos'),
    path('productos/lista/', views.lista_productos, name='lista_productos'),
    path('carrito/', views.carrito, name='carrito'),
    path('contador-carrito/', views.contador_carrito, name='contador_carrito'),
    path('agregar-al-carrito/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('carrito/incrementar/<int:item_index>/', views.incrementar_cantidad, name='incrementar_cantidad'),
    path('carrito/decrementar/<int:item_index>/', views.decrementar_cantidad, name='decrementar_cantidad'),
    path('carrito/eliminar/<int:item_index>/', views.eliminar_item, name='eliminar_item'),
    path('usuarios/tipo-entrega/', views.tipo_entrega, name='tipo_entrega'),
    path('retiro-local/', views.retiro_local, name='retiro_local'),
    path('resumen/', views.resumen_pedido, name='resumen_pedido'),
    path('pedido/confirmar-pedido/', views.confirmar_pedido, name='confirmar_pedido'), 
    path('pedido/pedido-confirmado/', views.confirmacion_pedido, name='pedido_confirmado'),
    #Rutas para pruebas de orden de pedidos
    #Empleado/Cajero
    path('orden/', views.ordenes_view, name='ordenes_view'),
    #Cocina
    path('cocina/', views.cocina_view, name='cocina_view'),
]

usuarios/urls.py
from django.urls import path
from .import views

app_name = 'usuarios'

urlpatterns = [
    path('usuarios/', views.index, name='index'),
    path('usuarios/registro/', views.registro_cliente, name='registro'),
    path('usuarios/sesion/', views.iniciar_sesion, name='sesion'),
]

pedidos/forms.py
from django import forms
from datetime import datetime, time, timedelta

class RetiroForm(forms.Form):
    tipo_entrega = forms.CharField(widget=forms.HiddenInput(), initial='RE')
    hora_retiro = forms.TimeField(
        widget=forms.TimeInput(attrs={
            'type': 'time',
            'min': '19:00',
            #'max': '23:00'
            }),
        label='Hora estimada'
    )

    #def clean_hora_retiro(self):
    #    hora = self.cleaned_data['hora_retiro']
    #    ahora = (datetime.now() + timedelta(minutes=15)).time()

    #    if hora < time(19, 0) or hora > time(23, 0):
    #        raise forms.ValidationError("La hora debe estar entre las 19:00 y las 23:00.")
    #    if hora <= ahora:
    #        raise forms.ValidationError("Debe seleccionar una hora con al menos 15 minutos de anticipación.")
    #    return hora

pedidos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from administrador.models import Producto, CategoriaProducto, Cliente, IngredienteProducto
from django.contrib.auth.decorators import login_required
from .models import Adicional, Pedido, DetallePedido, DetalleAdicionalPedido, IngredienteEliminadoPedido
from .forms import RetiroForm
from django.db import transaction
from django.contrib import messages
from django.http import HttpResponse
from django.template.loader import render_to_string

def index(request):
    return render(request, 'pedidos/index.html')

def menu_productos(request):
    categorias = CategoriaProducto.objects.all()
    adicionales = Adicional.objects.all()
    carrito = request.session.get('carrito', [])
    
    # Total de item para el contador del carrito
    cantidad_carrito = sum(item['cantidad'] for item in carrito)

    return render(request, 'pedidos/menu_productos.html', {
        'categorias': categorias,
        'adicionales': adicionales,
        'cantidad_carrito': cantidad_carrito
        })

def lista_productos(request):
    categoria_nombre = request.GET.get('categoria')
    if categoria_nombre:
        productos = Producto.objects.filter(estado='A', categoria__nombre_categ=categoria_nombre)
    else:
        productos = Producto.objects.filter(estado='A')
    return render(request, 'pedidos/partials/productos_lista.html', {'productos': productos})

def contador_carrito(request):
    carrito = request.session.get('carrito', [])
    total = sum(item['cantidad'] for item in carrito)
    html = render_to_string('pedidos/partials/contador_carrito.html', {'cantidad': total})
    return HttpResponse(html)

def agregar_al_carrito(request):
    if request.method == 'POST':
        producto_id = request.POST.get('producto_id')
        adicionales_ids = request.POST.getlist('adicional[]', [])
        sin = request.POST.getlist('sin[]', [])
        comentario = request.POST.get('comentarios', '').strip().lower()

        producto = get_object_or_404(Producto, id=producto_id)
        adicionales = Adicional.objects.filter(id__in=adicionales_ids)

        # Normalizamos listas para comparacion
        adicionales_ids_sorted = sorted([str(a.id) for a in adicionales])
        sin_sorted = sorted(sin)

        # Estructura básica del carrito en sesión
        carrito = request.session.get('carrito', [])

        # Verificamos si ya existe el mismo item
        item_encontrado = False
        for item in carrito:
            if (
                item['producto'] == producto.id and 
                sorted([str(a['id']) for a in item['adicionales']]) == adicionales_ids_sorted and
                sorted(item['sin']) == sin_sorted and
                item['comentario'].strip().lower() == comentario
            ):
                # Ya existe, sumamos cantidad
                item['cantidad'] += 1
                item_encontrado = True
                break
        
        if not item_encontrado:
            # Agregamos el producto con sus detalles
            nuevo_item = {
                'producto': producto.id,
                'nombre': producto.nombre,
                'precio': producto.precio,
                'imagen': producto.imagen.url if producto.imagen else '',
                'personalizable': True if sin or adicionales_ids or comentario else False,
                'adicionales': [
                    {'id': a.id, 'nombre': a.nombre, 'precio': a.precio}
                    for a in adicionales
                ],
                'sin': sin,
                'comentario': comentario,
                'cantidad': 1,
                'subtotal': producto.precio + sum(a.precio for a in adicionales) # calculamos subtotal inicial
            }
            carrito.append(nuevo_item)

        request.session['carrito'] = carrito

    request.session['carrito'] = carrito
    return HttpResponse(status=204)

def carrito(request):
    carrito = request.session.get('carrito', [])

    # Calcular subtotal por producto y total general
    for item in carrito:
        total_adicionales = sum(a['precio'] for a in item['adicionales'])
        item['subtotal'] = (item['precio'] + total_adicionales) * item['cantidad']

    # Calculamos el total general
    total = sum(item['subtotal'] for item in carrito)

    # Total de item para el contador del carrito
    cantidad_carrito = sum(item['cantidad'] for item in carrito)

    return render(request, 'pedidos/carrito.html', {
            'carrito': carrito,
            'total': total,
            'cantidad_carrito': cantidad_carrito
        })
    
def _calcular_totales_y_actualizar_sesion(request, carrito):
    # Recalcular subtotal de cada item
    for item in carrito:
        total_adicionales = sum(a['precio'] for a in item['adicionales'])
        item['subtotal'] = (item['precio'] + total_adicionales) * item['cantidad']
    
    # Total general
    total = sum(item['subtotal'] for item in carrito)

    # Actualizar la sesion
    request.session['carrito'] = carrito
    return total

def incrementar_cantidad(request, item_index):
    carrito = request.session.get('carrito', [])
    

    if 0 <= item_index < len(carrito) and carrito[item_index]['cantidad'] < 10:
        carrito[item_index]['cantidad'] += 1
    
    total = _calcular_totales_y_actualizar_sesion(request, carrito)

    context = {
        'carrito': carrito,
        'total': total,
    }
    return render(request, 'pedidos/partials/contenido_carrito.html', context)

def decrementar_cantidad(request, item_index):
    carrito = request.session.get('carrito', [])
    if 0 <= item_index < len(carrito) and carrito[item_index]['cantidad'] > 1:
        carrito[item_index]['cantidad'] -= 1
    
    total = _calcular_totales_y_actualizar_sesion(request, carrito)

    context = {
        'carrito': carrito,
        'total': total,
    }

    return render(request, 'pedidos/partials/contenido_carrito.html', context)

def eliminar_item(request, item_index):
    carrito = request.session.get('carrito', [])
    if 0 <= item_index < len(carrito):
        carrito.pop(item_index)
    total = _calcular_totales_y_actualizar_sesion(request, carrito)

    if not carrito:
        return render (request, 'pedidos/partials/carrito_vacio.html')
    
    context = {
        'carrito': carrito,
        'total': total,
    }
    
    return render(request, 'pedidos/partials/contenido_carrito.html', context)

@login_required
def tipo_entrega(request):
    form = RetiroForm()
    return render(request, 'pedidos/tipo_entrega.html', {'form': form})

@login_required
def retiro_local(request):
    if request.method == 'POST':
        form = RetiroForm(request.POST)
        if form.is_valid():
            # Guardar los datos en la sesion
            request.session['tipo_entrega'] = form.cleaned_data['tipo_entrega']
            request.session['hora_retiro'] = form.cleaned_data['hora_retiro'].strftime('%H:%M')
            request.session['direccion'] = 'N/A'

            return redirect('pedidos:resumen_pedido')
    else:
        form = RetiroForm()
    return render(request, 'pedidos/tipo_entrega.html', {'form': form})

@login_required
def resumen_pedido(request):
    carrito = request.session.get('carrito', [])

    if not carrito:
        # Redirige si el carrito está vacío
        return redirect('pedidos:menu_productos')

    # Simulamos tipo de entrega (esto luego se recupera desde POST o session)
    tipo_entrega = request.session.get('tipo_entrega')  # o 'delivery'
    hora_estimada = request.session.get('hora_retiro')  # Simulado
    direccion = request.session.get('direccion')  # Solo si es delivery

    # Calcular total
    total = sum(item['subtotal'] for item in carrito)

    context = {
        'carrito': carrito,
        'total': total,
        'tipo_entrega': tipo_entrega,
        'hora_estimada': hora_estimada,
        'direccion': direccion,
    }

    return render(request, 'pedidos/resumen_pedido.html', context)

@login_required
def confirmar_pedido(request):
    carrito = request.session.get('carrito', [])
    if not carrito:
        messages.error(request, "Tu carrito está vacío")
        return redirect('pedidos:menu_productos')

    tipo_entrega = request.session.get('tipo_entrega')
    hora_retiro_str = request.session.get('hora_retiro')
    direccion = request.session.get('direccion', '')

    try:
        cliente = Cliente.objects.get(user=request.user)
    except Cliente.DoesNotExist:
        messages.error(request, "No se encontró un cliente asociado a tu usuario")
        return redirect('pedidos:menu_productos')

    from datetime import datetime
    hora_retiro = None
    if hora_retiro_str:
        try:
            hora_retiro = datetime.strptime(hora_retiro_str, '%H:%M').time()
        except ValueError:
            hora_retiro = None

    total = sum(item['subtotal'] for item in carrito)

    try:
        with transaction.atomic():
            pedido = Pedido.objects.create(
                cliente=cliente,
                total=total,
                tipo_entrega=tipo_entrega,
                hora_retiro=hora_retiro,
                direccion_entrega=direccion if tipo_entrega == 'DE' else '',
                estado='Pendiente',
            )

            for item in carrito:
                producto = Producto.objects.get(pk=item['producto'])
                detalle = DetallePedido.objects.create(
                    pedido=pedido,
                    producto=producto,
                    cantidad=item['cantidad'],
                    precio_unitario=item['precio'],
                    nota=item.get('nota', '')
                )

                adicionales = item.get('adicionales', [])
                for ad in adicionales:
                    adicional_obj = Adicional.objects.get(pk=ad['id'])
                    DetalleAdicionalPedido.objects.create(
                        detalle_pedido=detalle,
                        adicional=adicional_obj,

pedidos/templates/pedidos/carrito.html
{% extends 'pedidos/menu_productos.html' %}
{% load static %}

{% block body %}
    <div class="container my-5">
        <h2 class="text-center mb-4">🛒 Carrito de Compras</h2>

        {% if carrito %}
            <div id="carrito">
                <div class="table-responsive">
                    {% include 'pedidos/partials/lista_carrito.html' %}
                </div>

                <div class="d-flex justify-content-end mt-4">
                    <div class="text-end">
                        <h4><strong>Total: <span id="total-carrito">{{ total }} Gs</span></strong></h4>
                        <div class="d-flex gap-2 justify-content-end mt-2">
                            <a href="{% url 'pedidos:menu_productos' %}" class="btn btn-danger">Seguir comprando</a>
                            <a href="{% url 'usuarios:sesion' %}" class="btn btn-success">Continuar compra</a>
                        </div>
                    </div>
                </div>
            </div>

        {% else %}
            <div class="alert alert-info text-center">
                El carrito está vacío.
            </div>
        {% endif %}

    </div>
{% endblock %}

pedidos/templates/pedidos/confirmacion_pedido.html
<h1>SE GUARDO CORRECTAMENTE</h1>

pedidos/templates/pedidos/menu_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Iconos -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

        <!-- Fuente-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

        <!-- Estilos de Bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" />
        <!-- Estilos -->
        <link rel="stylesheet" href="{% static 'css/menu_productos.css' %}">
        {% block extra_css %}{% endblock %}
    </head>
    <body>
        <header class="header bg-dark">
            <h1>BROTHER'S BURGER</h1>
            <nav class="nav justify-content-center">
                <a href="{% url 'pedidos:index' %}">Inicio</a>
                <a href="{% url 'pedidos:menu_productos' %}">Productos</a>
                <a href="contacto.html">Contacto</a>
            </nav>

            <div class="contenedor">
                <input type="text" id="buscar" class="form-control w-50" placeholder="Buscar productos..." />
                
                <!-- Carrito -->
                <button id="carrito-btn" class="btn btn-warning ms-3">
                    <a href="{% url 'pedidos:carrito' %}" class="text-dark text-decoration-none">
                        <i class="bi bi-cart3"></i> (<span id="carrito-contador">
                        {% include 'pedidos/partials/contador_carrito.html' with cantidad=cantidad_carrito %}
                        </span>)
                    </a>
                </button>
            </div>
        </header>

        {% block body %}
        {% endblock %}

        <footer class="footer bg-dark">
            <p>Contacto: +595 971 123 456</p>
            <p>© 2024 The Burger. Todos los derechos reservados.</p>
        </footer>

        <!-- Toast de confirmación -->
        <div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 1055">
            <div id="toast-agregado" class="toast align-items-center text-white bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body">
                        ✅ Producto agregado al carrito
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Cerrar"></button>
                </div>
            </div>
        </div>



        <!-- Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- HTMX -->
        <script src="https://unpkg.com/htmx.org"></script>

        <script>
            document.body.addEventListener('htmx:afterRequest', function(evt) {
                const el = evt.detail.elt;
                //verifica si el form es de agregar al carrito
                if (el && el.classList.contains('form-agregar-al-carrito')){
                    //solo mostrar si aun no fue mostrado en esta sesion
                    if (!sessionStorage.getItem('notificacionAgregado')){
                        const toastEl = document.getElementById('toast-agregado');
                        const toast = new bootstrap.Toast(toastEl);
                        toast.show();
                        sessionStorage.setItem('notificacionAgregado', 'true');
                    }
                }
            });
        </script>

        <script>
            document.addEventListener('DOMContentLoaded', function () {
                // Para cuando el DOM no cambia (botón "Agregar")
                document.body.addEventListener('htmx:afterRequest', function (evt) {
                    if (evt.detail.elt && evt.detail.elt.classList.contains('actualiza-contador')) {
                        console.log('✅ actualizarContador (afterRequest)');
                        htmx.ajax('GET', "{% url 'pedidos:contador_carrito' %}", {
                            target: '#carrito-contador'
                        });
                    }
                });

                // Para cuando el carrito es reemplazado (botones: +, -, X)
                document.body.addEventListener('htmx:afterSwap', function (evt) {
                    if (evt.detail.target && evt.detail.target.id === 'carrito') {
                        console.log('🔁 Se actualizó el carrito (afterSwap)');
                        htmx.ajax('GET', "{% url 'pedidos:contador_carrito' %}", {
                            target: '#carrito-contador'
                        });
                    }
                });
            });
        </script>
    </body>
</html>

pedidos/templates/pedidos/menu_productos.html
{% extends 'pedidos/menu_layout.html' %}
{% load static %}

{% block title %}
Menu
{% endblock %}

{% block body %}
  <!-- Menú de categorías -->
  <div class="my-4 bg-dark p-2 rounded" style="width: 60%; margin: 0 auto;">
    <ul class="nav nav-pills justify-content-center" id="menu-categorias">
      <li class="nav-item">
        <button class="nav-link active bg-dark"
            hx-get="{% url 'pedidos:lista_productos' %}"
            hx-target="#productos-lista"
            hx-swap="innerHTML">
          Todo
        </button>
      </li>
      {% for categoria in categorias %}
        <li class="nav-item">
          <button class="nav-link bg-dark text-white"
            hx-get="{% url 'pedidos:lista_productos' %}?categoria={{ categoria.nombre_categ|urlencode }}"
            hx-target="#productos-lista"
            hx-swap="innerHTML">
            {{ categoria.nombre_categ }}
          </button>
        </li>
      {% endfor %}
    </ul>
  </div>
  <!-- Productos -->
  <section id="productos" class="container">
    <h2 class="text-center mb-4">Nuestros Productos</h2>
    <!-- Contenedor para htmx -->
    <div 
        hx-get="{% url 'pedidos:lista_productos' %}"
        hx-trigger="load"
        hx-target="#productos-lista"
        hx-swap="innerHTML">
        <!-- Se insertan los productos dinamicamente -->
        <div  id="productos-lista" class="productos-grid">
        </div>
    </div>
      <!-- Modal -->
    <div class="modal fade" id="personalizarModal" tabindex="-1" aria-labelledby="personalizarModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <form
              id="form-personalizado"
              hx-post="{% url 'pedidos:agregar_al_carrito' %}"
              hx-swap="none"
              hx-trigger="submit"
              class="actualiza-contador">

              >
            <input type="hidden" name="producto_id" id="input-producto-id">
            {% csrf_token %}
            <div class="modal-header">
              <h5 class="modal-title" id="personalizarModalLabel">Personalizar Pedido</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body">
              <!-- Adicionales -->
              <div class="mb-4">
                <h6 class="fw-bold">Adicionales</h6>
                {% for adicional in adicionales %}
                  <div class="form-check">
                      <input class="form-check-input" type="checkbox" name="adicional[]" value="{{ adicional.id }}" id="adicional-{{ adicional.id }}">
                      <label class="form-check-label" for="adicional-{{ adicional.id }}">{{ adicional.nombre }} <span class="text-muted">+ Gs{{ adicional.precio }}</span>
                      </label>
                  </div>
                {% endfor %}
              </div>
              <!-- Sin -->
              <div class="mb-4">
                <h6 class="fw-bold">Sin</h6>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" name="sin[]" value="lechuga" id="lechuga">
                  <label class="form-check-label" for="lechuga">Sin lechuga</label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" name="sin[]" value="cebolla" id="cebolla">
                  <label class="form-check-label" for="cebolla">Sin cebolla</label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" name="sin[]" value="tomate" id="tomate">
                  <label class="form-check-label" for="tomate">Sin tomate</label>
                </div>
              </div>
              <!-- Comentarios -->
              <div class="mb-3">
                <label for="comentarios" class="form-label">Nota especial (comentario)</label>
                <input type="text" class="form-control" id="comentarios" name="comentarios" placeholder="Nota del producto">
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-primary">Agregar al carrito</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>

   <!-- Carga el input con el producto_id seleccionado -->
  <script>
    function cargarDatosProducto(boton) {
      const productoId = boton.getAttribute('data-producto-id');
      const productoNombre = boton.getAttribute('data-producto-nombre');

      // Rellenar el campo hidden con el ID del producto
      document.getElementById('input-producto-id').value = productoId;

      // (Opcional) Cambiar el título del modal
      document.getElementById('personalizarModalLabel').textContent = "Personalizar " + productoNombre;
    }
  </script>
{% endblock %}

pedidos/templates/pedidos/resumen_pedido.html
{% extends 'pedidos/menu_productos.html' %}
{% load static %}

{% block body %}
<div class="container my-5">

    {% if messages %}
        <div class="container mt-3">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Cerrar"></button>
            </div>
            {% endfor %}
        </div>
    {% endif %}

    <h2 class="text-center mb-4">📦 Resumen de tu pedido</h2>

    <!-- Información adicional del pedido -->
    <div class="mb-4">
        <div class="card shadow-sm">
            <div class="card-body">
                <h5 class="card-title">📝 Detalles del pedido</h5>
                <p><strong>Tipo de entrega:</strong>
                    {% if tipo_entrega == 'RE' %}Retiro en local{% elif tipo_entrega == 'DE' %} Delivery{% endif %}
                </p>
                {% if tipo_entrega == 'RE' %}
                    <p><strong>Hora estimado: </strong>{{ hora_estimada }}</p>
                {% elif tipo_entrega == 'DE' %}
                    <p><strong>Dirección de entrega:</strong>{{ direccion }}</p>
                    <p><strong>Costo de envio:</strong>5.000gs</p> <!-- Futuramente dinamico -->
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Lista de productos en el pedido -->
    <div id="carrito">
        <div class="table-responsive">
            {% include 'pedidos/partials/lista_carrito.html' %}
        </div>
        <h4>PRUEBA</h4>
        <pre>{{ carrito|safe }}</pre>
        <!-- Total y botón de confirmar -->
        <div class="d-flex justify-content-end mt-4">
            <div class="text-end">
                <h4><strong>Total a pagar: <span id="total-carrito">{{ total }} Gs</span></strong></h4>

                <form action="{% url 'pedidos:confirmar_pedido' %}" method="post" class="mt-3">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success btn-lg">✅ Confirmar pedido</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}